import "../styles/globals.css";
import type { Metadata } from "next";
import Provider from "./_trpc/provider";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className="bg-[#F8F8F8]">
      <Provider>{children}</Provider></body>
    </html>
  );
}
